### ISSUE TITLE
Change about us text

### ISSUE THREAD

**Issue by gulraeezgulshan** [gulraeezgulshan/seotech.github.io#4]
Change the text below 

From : Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud

To: Salim Habi University

**Comment by cmkor** [comment]
I want to work on this issue. I am working

**Comment by gulraeezgulshan** [comment]
Ok please complete this asap.

**Comment by gulraeezgulshan** [comment]
ok it seems fine
